export const SOURCE_NAME: string = "ACCOUNT_DELETION"
export const ACCOUNT_DELETION_GET_DATA: string = `${SOURCE_NAME}/LIST_PAGE/GET_DATA`;
export const ACCOUNT_DELETION_GET_DATA_SUCCESS: string = `${SOURCE_NAME}/LIST_PAGE/GET_DATA/SUCCESS`;