export const SOURCE_NAME: string = "ACCOUNT_DELETION";
export const SOURCE_NAME_URL: string = "account-deletion";
// List Page
export const ACCOUNT_DELETION_GET_DATA: string = `${SOURCE_NAME}/LIST_PAGE/GET_DATA`;
export const ACCOUNT_DELETION_GET_DATA_SUCCESS: string = `${SOURCE_NAME}/LIST_PAGE/GET_DATA/SUCCESS`;

// Form Page
export const ACCOUNT_DELETION_GET_ONE_RECORD: string = `${SOURCE_NAME}/FORM_PAGE/GET_ONE`;
export const ACCOUNT_DELETION_GET_ONE_RECORD_SUCCESS: string = `${SOURCE_NAME}/FORM_PAGE/GET_ONE/SUCCESS`;
